#!/bin/bash

source /home/fredericokremer/miniconda3/bin/activate

eval "$(/home/fredericokremer/miniconda3/bin/./conda shell.bash hook)"

conda activate
conda activate bambu-server

#redis-server &

make deploy
